version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
  
  nacos:
    image: nacos/nacos-server:v3.2.0
    container_name: nacos
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone
      NACOS_AUTH_TOKEN: YS12ZXJ5LWxvbmctYW5kLXNlY3VyZS1zZWNyZXQta2V5LWZvci1uYWNvcy0yMDI1
      NACOS_AUTH_IDENTITY_KEY: nacos-auth-identity
      NACOS_AUTH_IDENTITY_VALUE: nacos-auth-identity-value
    volumes:
      - ./nacos/logs:/home/nacos/logs
    restart: always
  
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes --requirepass password
    restart: always
  
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./rustfs/data:/data
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin123
      RUSTFS_CONSOLE_ENABLE: "true"
    command: --console-enable /data
    restart: always